activities:
  path: /activities
  controller: App\Controller\GetAllActivitiesController::getActivities
  methods: GET

add_activity:
  path: /addActivity
  controller: App\Controller\AddActivityController::addActivity
  methods: POST

register_activity:
  path: /registerActivity
  controller: App\Controller\MainController:registerActivity
  methods: POST

nextActivity:
  path: /nextActivity
  controller: App\Controller\MainController::nextActivity
  methods: GET